# Site settings
title: 18F Testing Cookbook
email: shawn.allen@gsa.gov
description: >
  The 18F Testing Cookbook contains recipes and best practices for automated
  and manual testing in lots of different environments, languages, stacks and
  platforms.
url: "http://pages.18f.gov/testing-cookbook/"
github_username: 18F

# Build settings
exclude:
- Gemfile
- Gemfile.lock
- go

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# DOCter bits after this

name: Testing Cookbook
subtitle:

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: JavaScript testing
  url: javascript/
  internal: true
  children:
  - text: Mocha in Node
    url: node-mocha/
    internal: true
  - text: JavaScript testing examples
    url: examples/
    internal: true
- text: Python testing
  url: python/
  internal: true
  children:
  - text: Python testing with nose
    url: nose/
    internal: true
- text: Ruby testing
  url: ruby/
  internal: true
- text: Go testing
  url: go/
  internal: true
- text: Browser testing
  url: browser/
  internal: true
  children:
  - text: Automation
    url: automation/
    internal: true
  - text: Selenium and Sauce Labs
    url: selenium-sauce/
    internal: true
  - text: Browser testing services
    url: services/
    internal: true
  - text: VirtualBox
    url: virtualbox/
    internal: true
- text: Load testing
  url: load/
  internal: true

repos:
- name: 18F Testing Cookbook
  description: Main repository
  url: https://github.com/18F/testing-cookbook

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
