# Site settings
title: 18F Testing Cookbook
email: shawn.allen@gsa.gov
description: >
  The 18F Testing Cookbook contains recipes and best practices for automated
  and manual testing in lots of different environments, languages, stacks and
  platforms.
baseurl: "/testing-cookbook"
url: "http://18f.github.io/testing-cookbook/"
github_username:  shawnbot

# Build settings
markdown: redcarpet
exclude:
- README.md
- LICENSE.md
- CONTRIBUTING.md
- deploy
- vendor
- go

permalink: pretty

# DOCter bits after this

name: Testing Cookbook
subtitle:

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: JavaScript
  url: javascript/
  internal: true
- text: Python
  url: python/
  internal: true
- text: Ruby
  url: ruby/
  internal: true
- text: Browser Testing
  url: browser/
  internal: true

repos:
- name: 18F Testing Cookbook
  description: Main repository
  url: https://github.com/18F/testing-cookbook

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19
